id: P21429BB6
initial_creation_type: input
source_metadata:
  title: Nepal Series
  language: en
  description: 'Texts related to the kingdom of Nepal, known to Tibetans as the ''land
    of wool'' (bal yul):'
  volume:
    a20f28bba73042a4992b32a2a45c183b:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Guides
    b9c51d4a46ae47498f818c6771b7572d:
      title: A Short Guide to Yangleshö in Nepal
      parent: Guides
    7f1054d23eeb44f789aea1dbd876a075:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: History
    6fb3a54a9cf7452185cc46c8df84fe46:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Offering
    36a9c1efbd9948d19c789d5386d288a1:
      title: In Praise of Yangleshö in Nepal
      parent: Praise
    5cee0093dec44f5b9c19d139a03d82b5:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Praise
    8b5e67f7b06d4ad28e688da8099c50bf:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Praise
    01f86ae6253649928035689ed9fc77f3:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    d6eafbddb2c341c0a242a89befdbd79f:
      title: A Prayer to the Stūpa of Jarung Khashor in Boudha
      parent: Prayers
    2d0bf8b1684b42c59c901bb4ea6258d1:
      title: A Prayer to the Svayambhū Stūpa in Nepal
      parent: Prayers
    8a0db7e89a8f4c0395dc96828fde2f3c:
      title: A Prayer to the Three Stūpas of Nepal
      parent: Prayers
    d66fac2e1abf4d84a930673d2ec29c1d:
      title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice
        to the Tigress
      parent: Prayers
    a58f317c4a56472d8e11a8ebc001c774:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Songs
    02404ab6bf3049f7b35a7e7437732314:
      title: Upon Arriving at Yangleshö
      parent: Songs
created_at: '2022-03-01T04:47:23.840036'
last_modified_at: '2022-03-01T04:47:23.840042'
